### ISSUE TITLE
Foundational Reference Implementation | Connected links broken

### ISSUE THREAD

**Issue by geralexgr** [Azure/Mission-Critical#6]
**Describe the bug**
Foundational Reference Implementation | Connected links are broken on README.md
https://github.com/azure/alwayson-foundational-connected

**Comment by sebader** [comment]
This repo is not yet Public - but very close to being :) should happen in the next few days. Hence the link appears broken for you.
 I'll update the issue once done

**Comment by sebader** [comment]
The Foundational-Connected repo is now public! :)
