### ISSUE TITLE
Incomplete sentence re deployment stamps

### ISSUE THREAD

**Issue by kw217** [Azure/Mission-Critical#7]
**Describe the bug**
The sentence "Regional (Stamp) Resources: those that are deployed" stops before it's finished. I think you meant to say something like "multiple times, once for each stamp" or similar.

**To Reproduce**
Look at https://github.com/Azure/AlwaysOn/blob/de4e489a8af6013210b71e73e17af0e6a4383085/docs/design-methodology/Deployment-Testing.md?plain=1#L165

**Expected behavior**
Sentence should continue to a conclusion and end with a period.

**Comment by hjscherer** [comment]
@kw217, thank you very much for the feedback. We'll clarify that in our next update.
