### ISSUE TITLE
Stray sentence re release branch

### ISSUE THREAD

**Issue by kw217** [Azure/Mission-Critical#8]
**Describe the bug**
Under "Branching strategy" after the Design Considerations bullets there seems to be some stray text re "release branch with a subsequently deployment". This should probably be deleted or edited to make sense.

**To Reproduce**
Go to https://github.com/Azure/AlwaysOn/blob/de4e489a8af6013210b71e73e17af0e6a4383085/docs/design-methodology/Deployment-Testing.md?plain=1#L238

**Comment by hjscherer** [comment]
Thank you for your feedback. We'll update and clarify that shortly.
